import type { AgentOperabilityReport, GeneratedArtifact } from "../schemas.js";

export function generateWellKnownArtifacts(report: AgentOperabilityReport): GeneratedArtifact[] {
  return [
    {
      path: ".well-known/agents.json",
      mediaType: "application/json",
      content: `${JSON.stringify(generateAgentsManifest(report), null, 2)}\n`
    },
    {
      path: ".well-known/mcp.json",
      mediaType: "application/json",
      content: `${JSON.stringify(generateMcpDraft(report), null, 2)}\n`
    },
    {
      path: ".well-known/agent-skills/index.json",
      mediaType: "application/json",
      content: `${JSON.stringify(generateAgentSkillsIndex(report), null, 2)}\n`
    }
  ];
}

export function generateAgentsManifest(report: AgentOperabilityReport): Record<string, unknown> {
  const root = report.site.rootUrl.replace(/\/$/, "");

  return {
    version: "0.1",
    generatedBy: "AgentLayer",
    generatedAt: report.generatedAt,
    site: {
      name: report.site.name,
      rootUrl: report.site.rootUrl,
      summary: report.site.summary
    },
    urls: {
      llmsTxt: `${root}/llms.txt`,
      llmsFullTxt: `${root}/llms-full.txt`,
      siteProfile: `${root}/site-profile.json`,
      facts: `${root}/facts.json`,
      actions: `${root}/actions.json`,
      policies: firstPageUrl(report, ["privacy", "terms"]),
      contact: firstPageUrl(report, ["contact", "demo", "support"])
    },
    actions: report.actions.map((action) => ({
      name: action.name,
      url: action.url,
      actionType: action.actionType,
      requiresHumanConfirmation: action.requiresHumanConfirmation,
      sensitivity: action.sensitivity
    }))
  };
}

export function generateMcpDraft(report: AgentOperabilityReport): Record<string, unknown> {
  return {
    name: report.site.name,
    url: report.site.rootUrl,
    experimental: true,
    note:
      "This file is generated by AgentLayer as a discovery-oriented draft. Validate against the latest MCP Server Card specification before production use.",
    generatedAt: report.generatedAt,
    description: report.site.summary,
    suggestedResources: [
      { name: "llms.txt", url: new URL("/llms.txt", report.site.rootUrl).toString() },
      { name: "facts.json", url: new URL("/facts.json", report.site.rootUrl).toString() },
      { name: "actions.json", url: new URL("/actions.json", report.site.rootUrl).toString() }
    ]
  };
}

export function generateAgentSkillsIndex(report: AgentOperabilityReport): Record<string, unknown> {
  return {
    generatedBy: "AgentLayer",
    generatedAt: report.generatedAt,
    experimental: true,
    skills: report.actions.map((action) => ({
      name: skillNameForAction(action.name),
      description: action.description,
      url: action.url,
      sourceUrl: action.sourceUrl,
      requiresHumanConfirmation: action.requiresHumanConfirmation
    }))
  };
}

function skillNameForAction(actionName: string): string {
  const names: Record<string, string> = {
    book_demo: "book_demo",
    contact_sales: "contact_sales",
    open_api_docs: "read_api_docs",
    open_security_page: "read_security_docs",
    read_privacy_policy: "read_privacy_policy",
    read_terms: "read_terms",
    request_support: "request_support",
    search_docs: "search_docs",
    view_pricing: "find_pricing"
  };

  return names[actionName] ?? actionName;
}

function firstPageUrl(report: AgentOperabilityReport, pageTypes: readonly string[]): string | null {
  return report.scan.pages.find((page) => pageTypes.includes(page.pageType))?.finalUrl ?? null;
}
