import type { AgentOperabilityReport, GeneratedArtifact } from "../schemas.js";

export function generateWellKnownArtifacts(report: AgentOperabilityReport): GeneratedArtifact[] {
  return [
    {
      path: ".well-known/agents.json",
      mediaType: "application/json",
      content: `${JSON.stringify(generateAgentsManifest(report), null, 2)}\n`
    },
    {
      path: ".well-known/mcp.json",
      mediaType: "application/json",
      content: `${JSON.stringify(generateMcpDraft(report), null, 2)}\n`
    },
    {
      path: ".well-known/mcp/server-card.json",
      mediaType: "application/json",
      content: `${JSON.stringify(generateMcpServerCardDraft(report), null, 2)}\n`
    },
    {
      path: ".well-known/api-catalog",
      mediaType: "application/json",
      content: `${JSON.stringify(generateApiCatalogDraft(report), null, 2)}\n`
    },
    {
      path: ".well-known/agent-skills/index.json",
      mediaType: "application/json",
      content: `${JSON.stringify(generateAgentSkillsIndex(report), null, 2)}\n`
    }
  ];
}

export function generateAgentsManifest(report: AgentOperabilityReport): Record<string, unknown> {
  const root = report.site.rootUrl.replace(/\/$/, "");

  return {
    version: "0.1",
    generatedBy: "AgentLayer",
    generatedAt: report.generatedAt,
    draft: true,
    standardStatus: "agent-discovery-draft",
    nonComplianceDisclaimer:
      "Generated by AgentLayer as a reviewable discovery artifact. This is not a claim of compliance with any official agents.json specification.",
    site: {
      name: report.site.name,
      rootUrl: report.site.rootUrl,
      summary: report.site.summary
    },
    urls: {
      llmsTxt: `${root}/llms.txt`,
      llmsFullTxt: `${root}/llms-full.txt`,
      siteProfile: `${root}/site-profile.json`,
      facts: `${root}/facts.json`,
      actions: `${root}/actions.json`,
      apiCatalog: `${root}/.well-known/api-catalog`,
      mcpServerCard: `${root}/.well-known/mcp/server-card.json`,
      agentSkills: `${root}/.well-known/agent-skills/index.json`,
      policies: firstPageUrl(report, ["privacy", "terms"]),
      contact: firstPageUrl(report, ["contact", "demo", "support"])
    },
    actions: report.actions.map((action) => ({
      name: action.name,
      url: action.url,
      actionType: action.actionType,
      requiresHumanConfirmation: action.requiresHumanConfirmation,
      sensitivity: action.sensitivity
    }))
  };
}

export function generateMcpDraft(report: AgentOperabilityReport): Record<string, unknown> {
  const root = report.site.rootUrl.replace(/\/$/, "");

  return {
    schema: "mcp-server-card-draft",
    name: report.site.name,
    url: report.site.rootUrl,
    serverCardUrl: `${root}/.well-known/mcp/server-card.json`,
    legacyAlias: true,
    experimental: true,
    draft: true,
    standardStatus: "mcp-server-card-draft-alias",
    nonComplianceDisclaimer:
      "Legacy AgentLayer alias for draft MCP discovery metadata. Use .well-known/mcp/server-card.json for the canonical generated draft; validate against the latest MCP Server Card draft before publishing.",
    note: "This file is generated by AgentLayer as a discovery-oriented draft. Validate against the latest MCP Server Card specification before production use.",
    generatedAt: report.generatedAt,
    description: report.site.summary,
    suggestedResources: [
      {
        name: "llms.txt",
        url: new URL("/llms.txt", report.site.rootUrl).toString()
      },
      {
        name: "facts.json",
        url: new URL("/facts.json", report.site.rootUrl).toString()
      },
      {
        name: "actions.json",
        url: new URL("/actions.json", report.site.rootUrl).toString()
      }
    ]
  };
}

export function generateMcpServerCardDraft(
  report: AgentOperabilityReport
): Record<string, unknown> {
  const root = report.site.rootUrl.replace(/\/$/, "");

  return {
    schema: "mcp-server-card-draft",
    version: "0.1",
    generatedBy: "AgentLayer",
    generatedAt: report.generatedAt,
    draft: true,
    standardStatus: "mcp-server-card-draft",
    nonComplianceDisclaimer:
      "Generated by AgentLayer for review. This is not an official MCP server implementation or compliance claim.",
    server: {
      name: report.site.name,
      url: report.site.rootUrl,
      description: report.site.summary
    },
    discovery: {
      agentsJson: `${root}/.well-known/agents.json`,
      llmsTxt: `${root}/llms.txt`,
      llmsFullTxt: `${root}/llms-full.txt`,
      apiCatalog: `${root}/.well-known/api-catalog`,
      agentSkills: `${root}/.well-known/agent-skills/index.json`
    },
    resources: [
      {
        name: "site-profile",
        type: "application/json",
        url: `${root}/site-profile.json`
      },
      { name: "facts", type: "application/json", url: `${root}/facts.json` },
      {
        name: "actions",
        type: "application/json",
        url: `${root}/actions.json`
      },
      { name: "report", type: "text/html", url: `${root}/report.html` }
    ],
    capabilities: {
      tools: report.actions.map((action) => ({
        name: skillNameForAction(action.name),
        description: action.description,
        sourceUrl: action.sourceUrl,
        requiresHumanConfirmation: action.requiresHumanConfirmation,
        sensitivity: action.sensitivity
      }))
    }
  };
}

export function generateApiCatalogDraft(report: AgentOperabilityReport): Record<string, unknown> {
  const apiPages = report.scan.pages.filter(
    (page) => page.pageType === "api_docs" || /api/i.test(page.finalUrl)
  );

  return {
    schema: "api-catalog-draft",
    version: "0.1",
    generatedBy: "AgentLayer",
    generatedAt: report.generatedAt,
    draft: true,
    standardStatus: "api-catalog-draft",
    nonComplianceDisclaimer:
      "Generated by AgentLayer from public pages. Review, complete, and validate this catalog before treating it as an authoritative API description.",
    site: {
      name: report.site.name,
      rootUrl: report.site.rootUrl
    },
    apis: apiPages.map((page) => ({
      title: page.title ?? page.headings.h1[0] ?? "API documentation",
      url: page.finalUrl,
      description: page.description ?? firstTextSnippet(page.visibleText)
    })),
    relatedActions: report.actions
      .filter((action) =>
        /api|docs|developer/i.test(`${action.name} ${action.description} ${action.url}`)
      )
      .map((action) => ({
        name: action.name,
        url: action.url,
        sourceUrl: action.sourceUrl
      }))
  };
}

export function generateAgentSkillsIndex(report: AgentOperabilityReport): Record<string, unknown> {
  return {
    schema: "agent-skills-index-draft",
    generatedBy: "AgentLayer",
    generatedAt: report.generatedAt,
    draft: true,
    experimental: true,
    standardStatus: "agent-skills-draft",
    nonComplianceDisclaimer:
      "Generated by AgentLayer as a draft skills index. Review action semantics and confirmation requirements before publishing or wiring to an agent runtime.",
    skills: report.actions.map((action) => ({
      name: skillNameForAction(action.name),
      description: action.description,
      url: action.url,
      sourceUrl: action.sourceUrl,
      requiresHumanConfirmation: action.requiresHumanConfirmation,
      sensitivity: action.sensitivity
    }))
  };
}

function skillNameForAction(actionName: string): string {
  const names: Record<string, string> = {
    book_demo: "book_demo",
    contact_sales: "contact_sales",
    open_api_docs: "read_api_docs",
    open_security_page: "read_security_docs",
    read_privacy_policy: "read_privacy_policy",
    read_terms: "read_terms",
    request_support: "request_support",
    search_docs: "search_docs",
    view_pricing: "find_pricing"
  };

  return names[actionName] ?? actionName;
}

function firstPageUrl(report: AgentOperabilityReport, pageTypes: readonly string[]): string | null {
  return report.scan.pages.find((page) => pageTypes.includes(page.pageType))?.finalUrl ?? null;
}

function firstTextSnippet(text: string): string | null {
  const snippet = text.replace(/\s+/g, " ").trim().slice(0, 240);
  return snippet.length > 0 ? snippet : null;
}
